import eslint from '@eslint/js';
import prettierConfig from 'eslint-config-prettier';
import reactHooks from 'eslint-plugin-react-hooks';
import tseslint from 'typescript-eslint';
// Generated by `wxt prepare` (runs on install); covers all WXT auto-import globals.
import wxtAutoImports from './apps/extension/.wxt/eslint-auto-imports.mjs';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/',
      '**/.output/',
      '**/.wxt/',
      '**/dist/',
      'playwright-report/',
      'test-results/',
      // Session-tooling scratch dir (not project code, self-gitignored).
      '.remember/',
    ],
  },
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['**/*.tsx'],
    plugins: { 'react-hooks': reactHooks },
    rules: reactHooks.configs.recommended.rules,
  },
  {
    files: ['apps/extension/**'],
    languageOptions: {
      globals: wxtAutoImports.languageOptions.globals,
    },
  },
  {
    // CLAUDE.md hard rule: packages/core stays free of browser APIs, and the
    // current date/time must be injected — never read inside core logic.
    files: ['packages/core/**'],
    rules: {
      'no-restricted-globals': [
        'error',
        'window',
        'document',
        'navigator',
        'chrome',
        'browser',
        'localStorage',
      ],
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['wxt', 'wxt/*', 'webextension-polyfill', 'react', 'react-dom', 'react-dom/*'],
              message: 'packages/core must stay free of browser/UI imports.',
            },
          ],
        },
      ],
      'no-restricted-syntax': [
        'error',
        {
          selector: "NewExpression[callee.name='Date'][arguments.length=0]",
          message: 'Inject `today: Date` as a parameter instead of calling new Date().',
        },
        {
          selector: "CallExpression[callee.object.name='Date'][callee.property.name='now']",
          message: 'Inject the current time as a parameter instead of calling Date.now().',
        },
      ],
    },
  },
  prettierConfig,
);
